# Generated by Django 5.2.6 on 2025-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('car_Name', models.CharField(max_length=10)),
                ('carID', models.IntegerField(primary_key=True, serialize=False)),
                ('fuelTupe', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=6)),
                ('brand', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
